name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        fetch-depth: 0
        submodules: true

    # Build the binary
    # override the compiler
    - run: git submodule update --init --recursive
    - run: nix-build -E '(with import <nixpkgs> {}; callPackage ./ci/nix/default.nix { })'
